language: node_js

node_js:
  - 'node'

cache:
  yarn: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5.1
    - g++-5.1

before_script:
  - bower install

script:
  - gulp build
