dist: trusty
language: node_js

node_js:
- node

env:
  global:
    - secure: TGFRkWTqhmYk93ih7MGUS8BKMAtLYf2LZHXr7lewfCdMLfpeHhcHaGZqz+VckfbYQ5Ad9NWTnRjrHa4SDHUEfJzIfB4RD/5iRk4W82oTwnkxCjLGoEU70Aaz8q6IW9YsbzdT+ZPffhlJbTc3hYAUKBca3eInAnVzjQBsqSItWF1BIb6zw2eh5Uy4sBgThODbuykrB5X6FY2Z23iAIO2wXyH2VpqQMSJUSn3dgsdzNhAgpkS/3gGPb3Dk2BRb7XzOYywCkAJ4M8DkxghvVsUcOwQvN9/NK/xb5kJUYTedhNOkSZ4xJFmHKzfhfjoxH/wHXPCGrYl+iKFnWbRQiz7rFnfOgT7pjNliFu0Oet6iMJ+K9tzrv1NmsH4vNrnGzzzq1/Eym6ImMykMEFBriHW5iGN9axTo7Bycug+CrgjS+ARoVLPvpJi0pq8PKPF1854RNdcHZ/uTVSjFY2tOkmfCAGCbCwJQ597cZgjjfA2/BZgjdxnyEbU/BYynF+GRll+JgXwD5vlMdMtrSvo5yC9uyX9nSX+aN6LZX2AgsLD6WFbSKlN4YfqS/hKmXR1puVq/Ctug8weHFGuQwfz0UVeh2UvIHeKugB4u4hPEegZUnkHMWwhdzgbPNlg047Unw/OZl81IhfCPlAMBx3BUXYJl6q8qDs8/J3UjzA65rWzHkMg=

before_script:
  - bower install

script:
  - gulp build

before_deploy:
  - (cd ./functions && npm install)

deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: "z9aBocF0dHE7/PvNHAsQ1tc6bDNbJX2ERkXP6g9IEQTWGaI9iHV7HxFQSBynoWaVZJjOSnSzPRKWbXZlzKKJ8NxR3KdkNT1ETP06FyanChN0JFxv1SLvsjuKuVlUdV9NzJ6WscQ7UbjCeJtszfJwN0iLHl8+pAWc/yaarEOQx5OfwIMTMpNVho4eH+sHx0BovcWDO8IHPZ6iSPEjrJrP4otlklG7yMuv0DeB2+f10eYH0WN5IX6fq4CFPM8uu6J0ZHKN0QYaiV1uF9dnL2YORuyYY1mUjnv8ZwjCzZmPBH480OzTxJC2IIfO/+cQsdB6A4v5wfz72+UuJIoZQNNYLI6KS1JCIeAojGBT3qubIJEE5Q49l8ES0GJA8SZB9npRtmPDE68t96rKGVj/ZLbK3cNgYP/G+Sdge5GI51WxItiHaGbah2vGtwuxBt42tJfb1AzxK5zb9X5f5HBi1y1FZLpEJvm88LUn7lEG4D7CiOuLP1mgEFh2FrboJK0yzWD+5wfaVV2PEHdH5CnvYA3S2g+1uAVYnvcKU6Nngfxk1k8K29DbJk1CA280uN4KsSA5HaAZ3KrTq6/IeVQoMfTRBhW0JXQ1xANrl5e0I3p5LuNFz6tFvDdf2nMDIwPLfo8LqY3s4aMA30dYJWjMj0yTy5gMrGHRjlf0XwtiUYeCiVc="
    project: "festify-dev"
    on:
      branch: develop
  - provider: firebase
    skip_cleanup: true
    token:
      secure: "z9aBocF0dHE7/PvNHAsQ1tc6bDNbJX2ERkXP6g9IEQTWGaI9iHV7HxFQSBynoWaVZJjOSnSzPRKWbXZlzKKJ8NxR3KdkNT1ETP06FyanChN0JFxv1SLvsjuKuVlUdV9NzJ6WscQ7UbjCeJtszfJwN0iLHl8+pAWc/yaarEOQx5OfwIMTMpNVho4eH+sHx0BovcWDO8IHPZ6iSPEjrJrP4otlklG7yMuv0DeB2+f10eYH0WN5IX6fq4CFPM8uu6J0ZHKN0QYaiV1uF9dnL2YORuyYY1mUjnv8ZwjCzZmPBH480OzTxJC2IIfO/+cQsdB6A4v5wfz72+UuJIoZQNNYLI6KS1JCIeAojGBT3qubIJEE5Q49l8ES0GJA8SZB9npRtmPDE68t96rKGVj/ZLbK3cNgYP/G+Sdge5GI51WxItiHaGbah2vGtwuxBt42tJfb1AzxK5zb9X5f5HBi1y1FZLpEJvm88LUn7lEG4D7CiOuLP1mgEFh2FrboJK0yzWD+5wfaVV2PEHdH5CnvYA3S2g+1uAVYnvcKU6Nngfxk1k8K29DbJk1CA280uN4KsSA5HaAZ3KrTq6/IeVQoMfTRBhW0JXQ1xANrl5e0I3p5LuNFz6tFvDdf2nMDIwPLfo8LqY3s4aMA30dYJWjMj0yTy5gMrGHRjlf0XwtiUYeCiVc="
    project: "festify-beta"
    on:
      branch: testing
  - provider: firebase
    skip_cleanup: true
    token:
      secure: "z9aBocF0dHE7/PvNHAsQ1tc6bDNbJX2ERkXP6g9IEQTWGaI9iHV7HxFQSBynoWaVZJjOSnSzPRKWbXZlzKKJ8NxR3KdkNT1ETP06FyanChN0JFxv1SLvsjuKuVlUdV9NzJ6WscQ7UbjCeJtszfJwN0iLHl8+pAWc/yaarEOQx5OfwIMTMpNVho4eH+sHx0BovcWDO8IHPZ6iSPEjrJrP4otlklG7yMuv0DeB2+f10eYH0WN5IX6fq4CFPM8uu6J0ZHKN0QYaiV1uF9dnL2YORuyYY1mUjnv8ZwjCzZmPBH480OzTxJC2IIfO/+cQsdB6A4v5wfz72+UuJIoZQNNYLI6KS1JCIeAojGBT3qubIJEE5Q49l8ES0GJA8SZB9npRtmPDE68t96rKGVj/ZLbK3cNgYP/G+Sdge5GI51WxItiHaGbah2vGtwuxBt42tJfb1AzxK5zb9X5f5HBi1y1FZLpEJvm88LUn7lEG4D7CiOuLP1mgEFh2FrboJK0yzWD+5wfaVV2PEHdH5CnvYA3S2g+1uAVYnvcKU6Nngfxk1k8K29DbJk1CA280uN4KsSA5HaAZ3KrTq6/IeVQoMfTRBhW0JXQ1xANrl5e0I3p5LuNFz6tFvDdf2nMDIwPLfo8LqY3s4aMA30dYJWjMj0yTy5gMrGHRjlf0XwtiUYeCiVc="
    project: "festify-79b08"
    on:
      branch: master

notifications:
  email: false
  slack:
    rooms:
      - secure: CB5ldw1lb5UhwTSikqyXQsfqTzfAAeoZ3sfrt5P4DTkP+FuUcAaj7n7sHwouuRdwmDrG7dcIHNywmvnVEmGFXwlmSy3Vcx/5hDtAfAm0YvUt1MUDm4NBRgOMqrSs8E75aZtAKlfV7eW1hTyS6idEH9CPJIgrd9ImG1SeBgz7ZmWdb5sZWg0OgUaWUeUerydhrsDQsuR5B721dvea249Y38FOhvGybTA8YDTViMEghuTOCKmZ/0Qaw1XavnbR/dxgVp4kxWJ6bG/vOHT0aB3Y17hckg97eGztHqjgBeF6Z6dn+Kt1rHW5trgjskmCCSfZiijRs4L1J7rGCcjAxc33BubMHOkXep59MM9gT78XCZadZkrQU2DFCq5icZPKaE4GLDFmR75CHIAh1jnr+IfQAzGILUs2LWzfabhmsy6m5QMDKNZJm5txN5X/cuZT2MDchC0BY0OElOVY6CBIpV5EJSl5XOcYGoTYXkdvqh1J7WnJmrAmlWwxQjLX+wpR1dutSo9kxfas9rB3zFCdFZ8Sj2aQj9kG5HLC9A7anj8EFs+ricHU/iprL+mrd8pFBWPsupVN6YE+xGAKFAoU0FZbuKLOfo1Et9coZwkchSTAWfJFhyJC54VOtquOtQ3Lhx8lmw3dfvGiXhQ+aetGO03c+e11XvgZpi2Aj9QOyxXYs8U=
    template:
      - "<%{build_url}|#%{build_number}> %{result}: <%{compare_url}|[%{repository_name}:%{branch}]> by %{author} (in %{duration})"
